name: Continuous Integration

on:
  push:
    branches:
      - '**'
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    inputs:
      python-version: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
      max-parallel: 3

  test:
    uses: ./.github/workflows/test.yml
    inputs:
      python-version: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
      api-url: ${{ vars.BR_UTILS_API_URL }}
      api-token: ${{ secrets.BR_UTILS_API_TOKEN }}
